version: '3'
services:
  jenkins-slave:
    build: .
    image: jenkins/jnlp-slave
    environment:
      - JENKINS_URL=http://192.168.99.100:8080/
      - JENKINS_AGENT_NAME=agent
      - JENKINS_SECRET=075182f37101d08ccca572f9fbb61522e0a642edf88d0905b61baba70a686196
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent