version: '3'
services:
  mysql:
    image: mysql:latest
#    build: .
#    restart: always
    volumes:
#      - .\data:/var/lib/mysql:rw
      - .\schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    environment:
      - MYSQL_ROOT_PASSWORD=N355Full5t4ck
#      - MYSQL_DATABASE=skill_matcher
      - MYSQL_USER=skillmatcher
      - MYSQL_PASSWORD=skillmatcher
    ports:
      - 3306:3306
